import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    'animate-in',
    'scroll-animate',
    'fade-up',
    'fade-down',
    'fade-left',
    'fade-right',
    'scale-up',
    'zoom-in',
    'bounce-in',
    'loaded',
    'error',
  ],
  theme: {
    extend: {
      colors: {
        'rose-pine': {
          base: '#191724',
          surface: '#1f1d2e',
          overlay: '#26233a',
          muted: '#7c7c9a',
          subtle: '#9c97b8',
          text: '#e0def4',
          love: '#eb6f92',
          gold: '#f6c177',
          rose: '#ebbcba',
          pine: '#3e8fb0',
          foam: '#9ccfd8',
          iris: '#c4a7e7',
          'highlight-low': '#21202e',
          'highlight-med': '#403d52',
          'highlight-high': '#524f67',
        },
        'rose-pine-moon': {
          base: '#232136',
          surface: '#2a273f',
          overlay: '#393552',
          muted: '#6e6a86',
          subtle: '#908caa',
          text: '#e0def4',
          love: '#eb6f92',
          gold: '#f6c177',
          rose: '#ea9a97',
          pine: '#3e8fb0',
          foam: '#9ccfd8',
          iris: '#c4a7e7',
          'highlight-low': '#2a283e',
          'highlight-med': '#44415a',
          'highlight-high': '#56526e',
        },
        'rose-pine-dawn': {
          base: '#faf4ed',
          surface: '#fffaf3',
          overlay: '#f2e9e1',
          muted: '#9893a5',
          subtle: '#797593',
          text: '#575279',
          love: '#b4637a',
          gold: '#ea9d34',
          rose: '#d7827e',
          pine: '#286983',
          foam: '#56949f',
          iris: '#907aa9',
          'highlight-low': '#f4ede8',
          'highlight-med': '#dfdad9',
          'highlight-high': '#cecacd',
        },
      },
    },
  },
  plugins: [],
};

export default config;
